spring.application.name=student
server.port=${PORT:8080}

# ── DATABASE (PostgreSQL) ─────────────────────────────────────────────
spring.datasource.url=${DB_URL:jdbc:postgresql://dpg-d82hjhbtqb8s73eedk0g-a.singapore-postgres.render.com/studentdb_axnj?sslmode=require}
spring.datasource.username=${DB_USERNAME:admin}
spring.datasource.password=${DB_PASSWORD:uNOelH27DQtaBThF6VG5oP877dES0KFd}
spring.datasource.driver-class-name=org.postgresql.Driver

# ── JPA ───────────────────────────────────────────────────────────────
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=always

# ── THYMELEAF ─────────────────────────────────────────────────────────
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
